// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBsx7afGxB6BL8uVnBgksZxWkudn0iT4o4',
    appId: '1:1038103380281:web:de213370c634589fbed8f9', // Placeholder if unknown, but same SenderID
    messagingSenderId: '1038103380281',
    projectId: 'acedup',
    authDomain: 'acedup.firebaseapp.com',
    storageBucket: 'acedup.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBsx7afGxB6BL8uVnBgksZxWkudn0iT4o4',
    appId: '1:1038103380281:android:123ed8bd82dcb50d1128e8',
    messagingSenderId: '1038103380281',
    projectId: 'acedup',
    storageBucket: 'acedup.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBsx7afGxB6BL8uVnBgksZxWkudn0iT4o4',
    appId: '1:1038103380281:ios:4c0be86064c73a4ebed8f9', // Placeholder
    messagingSenderId: '1038103380281',
    projectId: 'acedup',
    storageBucket: 'acedup.firebasestorage.app',
    iosBundleId: 'com.example.kairo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBsx7afGxB6BL8uVnBgksZxWkudn0iT4o4',
    appId: '1:1038103380281:ios:4c0be86064c73a4ebed8f9', // Placeholder
    messagingSenderId: '1038103380281',
    projectId: 'acedup',
    storageBucket: 'acedup.firebasestorage.app',
    iosBundleId: 'com.example.kairo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBsx7afGxB6BL8uVnBgksZxWkudn0iT4o4',
    appId: '1:1038103380281:web:3f904312948a6c76bed8f9', // Placeholder
    messagingSenderId: '1038103380281',
    projectId: 'acedup',
    authDomain: 'acedup.firebaseapp.com',
    storageBucket: 'acedup.firebasestorage.app',
  );
}
